name: Railway Bot Scheduler

on:
  workflow_dispatch:  # manuální spuštění
  schedule:           # automatické spuštění podle cronu
    - cron: "0 8 * * *"    # spustit bota v 08:00
    - cron: "59 23 * * *"  # zastavit bota v 23:59

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Railway CLI
        run: curl -sL https://railway.app/install.sh | sh
      - name: Login to Railway
        run: railway login --apiKey ${{ secrets.RAILWAY_API_KEY }}
      - name: Deploy project
        run: railway up --project ${{ secrets.RAILWAY_PROJECT_ID }} --detach
